#!/bin/bash

set -ex

mkdir $HOME/.jupyter
echo "c.NotebookApp.iopub_msg_rate_limit=1e22" >> $HOME/.jupyter/jupyter_notebook_config.py
echo "c.NotebookApp.iopub_data_rate_limit=1e22" >> $HOME/.jupyter/jupyter_notebook_config.py

flit install

cd /tmp/
#jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter labextension install ipytree jupyter-matplotlib jupyterlab-datawidgets jupyter-webrtc itkwidgets
